### ISSUE TITLE
call_user_func_array() expects parameter 1 to be a valid callback

### ISSUE THREAD

**Issue by rolandinsh** [rolandinsh/itempropwp#12]
https://wordpress.org/support/topic/some-php-strict-errors-with-itempropwp?replies=1

call_user_func_array() expects parameter 1 to be a valid callback, non-static method itempropwp::init() should not be called statically

call_user_func_array() expects parameter 1 to be a valid callback, non-static method itempropwp_review::reviewinit() should not be called statically

call_user_func_array() expects parameter 1 to be a valid callback, non-static method sidebar_generator::init() should not be called statically

**Comment by sireneweb** [comment]
others errors as : 
call_user_func_array() expects parameter 1 to be a valid callback, non-static method itempropwp::ipwp_the_content_filter() should not be called statically


call_user_func_array() expects parameter 1 to be a valid callback, non-static method itempropwp_review::review() should not be called statically

**Comment by rolandinsh** [comment]
if thsi is master rep, it's known issue like many others related to OOP and PHP
